name: ai2es
channels:
  - conda-forge
dependencies:
  - python=3.8
  - numpy
  - scipy
  - matplotlib
  - xarray
  - netcdf4
  - dask
  - pandas
  - scikit-learn
  - pyyaml
  - pytest
  - distributed
  - pip
  - pyproj
  - jupyter
  - jupyterlab
  - cartopy
  - tqdm
  - sphinx
  - numba
  - cython
  - pip:
    - tensorflow
    - tensorflow-probability
    - .
